### ISSUE TITLE
add support for remaining record content types

### ISSUE THREAD

**Issue by 0xmuralik** [cerc-io/laconic-sdk#24]
SIster of https://github.com/cerc-io/laconicd/issues/51

**Comment by 0xmuralik** [comment]
Blocked: https://github.com/cerc-io/laconic-sdk/issues/23

**Comment by i-norden** [comment]
I believe this was closed prematurely as was https://github.com/cerc-io/laconic-sdk/pull/27 because its sister issue is still pending https://github.com/cerc-io/laconicd/pull/79 and some of the changes there are still subject to change (which will require reflecting the changes back to here).

Also, since the unit tests were passing on https://github.com/cerc-io/laconic-sdk/pull/27 against the main branch of laconicd (missing the pending changes) this suggests to me that we are missing unit tests that cover the changes being made by these two PRs.
